[package]
name = "rust-rocket"
version = "0.1.0"
authors = ["alextanhongpin <alextan@seekasia.com>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"
serde = "1.0.29"
serde_json = "1.0.10"
serde_derive = "1.0.29"