version: '3.1'
services:
  db:
    image: postgres:10.3
    restart: always
    environment:
      # POSTGRES_USER: gorm
      # POSTGRES_PASSWORD: 123456
      POSTGRES_DB: rust_api
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
  
  api:
    image: alextanhongpin/rust-api
    environment:
      DATABASE_URL: posgres://postgres@docker.for.mac.localhost:5432/rust_api
    ports:
      - 8000:8000